config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'forms/new'
  get 'forms/edit'
  get '/2sign' => 'users#new'
  get 'staticpage/index'

 resources :forms
 resources :users
devise_for :students
  

resources :student do
  resources :form 
end

  devise_scope :student do
  authenticated :student do
    root 'forms#new', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

   

  resources :questions do
    member do
      put "like", to:    "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
   resources :comments
 end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :student
	has_many :comments
	  acts_as_votable
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_student!,except: [:index, :show]
  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order("created_at DESC")
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = current_student.questions.build
  end

  # GET /questions/1/edit
  def edit
  end

  # question /questions
  # question /questions.json
  def create
    @question = current_student.questions.build(question_params)
    respond_to do |format|
      if @question.save
        format.html { redirect_to questions_path, notice: '' }
        # format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    def upvote
    @question=Question.find(params[:id])
    @question.upvote_by current_student
    redirect_to questions_path
  end

  def downvote
    @question=Question.find(params[:id])
    @question.downvote_by current_student
    redirect_to questions_path
  end

#   def previous_question
#   self.class.first(:conditions => ["tile < ", tile], :order => "tile desc")
# end

# def next_question
#   self.class.first(:conditions => ["tile > ?", tile], :order => "tile asc")
# end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:tile, :body)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= simple_form_for(@question) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :tile %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>


<div class="col-sm-3"></div>
<div class="col-md-6">

<% @questions.each do |question| %>
<div class="container">
    <h2>
        <%= link_to question.tile, question %><br>
        <small class="author">Submitted
            <%= time_ago_in_words(question.created_at) %>
            by
  <div class="btn-group">
        <!-- <a class="btn btn-default btn-sm" href="<% questions_path %>">Visit question</a> -->
        <%= link_to like_question_path(question), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-up"></span>
        Upvote
        <%= question.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_question_path(question), method: :put, class: "btn btn-default btn-sm" do %>
        <span class="glyphicon glyphicon-chevron-down">
            Downvote
            <%= question.get_downvotes.size %>
            <% end %>
        </div>
    </div>
    <% end %>
  </h2>
            </div>
<div class="col-sm-3"></div>
<div class="col-md-6">

            <h1>New Post:</h1>
            <%= simple_form_for [@question, Question.new]  do |f| %>
  <div class="form-inputs">
    <%= f.input :tile %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>
</div>
</div>
<br>

<!-- 
<%= link_to 'New Question', new_question_path %>
 -->

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
  <h1><%= @question.tile %></h1><br>
	<p><%= @question.body %></p>
  <h4><small>Submitted by <%= @question.student.email %></small></h4>
</div>



<% if @question.student== current_student -%>
	<div class="btn-group">
		<%= link_to 'Edit', edit_question_path(@question), class: "btn btn-default" %>
		<%= link_to 'Delete', @question, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
	</div>
<% end %>



<!-- <p>
  <strong>Tile:</strong>
  <%= @question.tile %>
</p>

<p>
  <strong>Body:</strong>
  <%= @question.body %> -->
 </p><%= link_to "New_review",new_question_comment_path(@question),class: "btn btn-danger"%> 

<%= link_to 'Back', questions_path %>

<h3 class="comments_title">
  <%= @question.comments.count %> Comments
</h3>
<%= render :partial => @question.comments %>
<%= simple_form_for [@question, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <br>
  <%= f.submit "Add Comment", class: "btn btn-primary" %>
<% end %>
  