config/routes.rb
Rails.application.routes.draw do
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'forms/new'
  get 'forms/edit'
  get '/2sign' => 'users#new'
  get 'staticpage/index'

 resources :forms
 resources :users
devise_for :students
  

resources :student do
  resources :form 
end

  devise_scope :student do
  authenticated :student do
    root 'forms#new', as: :authenticated_root
  end

  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

   

  resources :questions do
    member do
      put "like", to:    "questions#upvote"
      put "dislike", to: "questions#downvote"
    end
   resources :comments
 end
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
# <div class="jumbotron" align="center">
# <h2> WELCOME TO ALUMINI PORTAL </h2>
#  <p>Hi, <b><%= current_student.regno %>!</b> <br>Please enroll your details by filling in the form below.</p>
#  <%= link_to new_form_path, class: "btn btn-default" do %>
#     <i class="glyphicon glyphicon-education"></i> Form
# <% end %>
#  <%= link_to staticpage_index_path, class: "btn btn-default" do %>
#     <i class="glyphicon glyphicon-ok"></i> Forum
# <% end %>
# </div>
#   <%= image_tag "sjit.jpg"%>
<div class="jumbotron"><h2 align="center"> Sign up </h2></div>
<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
<div class="col-md-4" align="center"></div>
   <div class="col-md-4">
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email,placeholder: "Email Id",class: "form-control",autofocus: true %>
  </div>
<div class="field">
    <%= f.label :rollno %><br/>
    <%= f.text_field :regno,placeholder: "Roll_No",class: "form-control",autofocus:true %>
  </div>
<% end%>
</div>
</div>